# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nagendra Posani
tagline:          'Personal Website'
description:      'A Computer Science Enthusiast, love to learn new technologies. <a href="mailto:nagendra@gatech.edu" target="_blank">Contact</a> me for any open source projects.'
url:              http://localhost:4000/
baseurl:          /


author:
  name:           'Nagendra Posani'
  url:            https://twitter.com/posaninagendra

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
gems: [jekyll-paginate, jekyll-gist]
