baseurl = "https://posaninagendra.github.io"

# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "Nagendra Posani"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');ga('create', '{{ site.google_analytics }}', 'auto');ga('send', 'pageview');"
hasCJKLanguage = true

[params]
	name = "Nagendra Posani"
	description = "My Excerpts"
	bio = "Computer Science enthusiast | Information Security & iOS Software Developer"
	# Enter optionally your twitter account
	twitter = "posaninagendra"
	enableRSS = false

	# Disqus comment
	disqusShortname = "nagendraposani"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = true

	# Duoshuo comment
	duoshuoShortname = "your_duoshuo_short_name"
	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	enableGithubIssuesTips = false

	# Enable googleAnalytics
	enableGoogleAnalytics = true

	# Enable baiduAnalytics
	enableBaiduAnalytics = false
	# Baidu Tongji Code
	baiduAnalytics = 'your_baidu_tongji_code'

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	tags = ""
	resume = ""

	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	github-square = "https://www.github.com/posaninagendra"
	linkedin-square = "https://www.linkedin.com/in/posaninagendra"
	facebook-square = "https://www.facebook.com/posaninagendra"
  twitter-square = "https://www.twitter.com/posaninagendra"
	medium-square = "https://www.medium.com/@posaninagendra"
